name: Trigger auto deployment for recipe-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/recipe-service-AutoDeployTrigger-667b8479-e132-4125-9a2c-dffe9f5769aa.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RECIPESERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RECIPESERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RECIPESERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: sandra.azurecr.io
          registryUsername: ${{ secrets.RECIPESERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RECIPESERVICE_REGISTRY_PASSWORD }}
          containerAppName: recipe-service
          resourceGroup: aiberlin
          imageToBuild: sandra.azurecr.io/recipe-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


